<?php
/**
 * @file
 * Functions to support theming in the custom_theme theme.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function custom_theme_preprocess_node(&$variables) {
  $node = $variables['node'];
  if ($variables['view_mode'] == 'listing') {
    $des = $node->get('field_design')->value;

    $new_view_mode = '';
    switch ($des) {
      case 'design1':
        $new_view_mode = 'design1';
        break;

      case 'design2' :
        $new_view_mode = 'design2';
        break;

      case 'design3' :
        $new_view_mode = 'design3';
        break;
    }

    if (!empty($new_view_mode)) {
      $view_builder = \Drupal::entityTypeManager()->getViewBuilder('node');
      $new_build = $view_builder->view($node, $new_view_mode);
      $variables['content'] = $new_build;
      $variables['view_mode'] = $new_view_mode;
    }

  }

}
